### ISSUE TITLE
OpenAPI property name results in incorrect method generation

### ISSUE THREAD

**Issue by CezaryBD** [micronaut-projects/micronaut-openapi#1226]
### Expected Behavior

I found a bug but not sure if Micronaut's or OpenAPI's.
Based on this example: https://guides.micronaut.io/latest/micronaut-openapi-generator-client-gradle-java.html

I expect to have getters and setters working and returning passed values.

### Actual Behaviour

I get null pointers.

### Environment Information

MacOS Ventura 13.6
openjdk 17.0.8 2023-07-18 LTS
OpenJDK Runtime Environment Corretto-17.0.8.7.1 (build 17.0.8+7-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.8.7.1 (build 17.0.8+7-LTS, mixed mode, sharing)

### Example Application

https://github.com/CezaryBD/reproducible-micronaut-openapi-casing-problem-01

### Version

4.1.1

**Comment by altro3** [comment]
@CezaryBD That's your mistake. You have mistake in openapi file. You changed field `temperature` to `atemperature`. Tha's why this field is null

![изображение](https://github.com/micronaut-projects/micronaut-openapi/assets/48474279/90205254-6226-47f1-90ff-b2ba75b49a7b)

**Comment by CezaryBD** [comment]
@altro3 I think there is a misunderstanding. The "mistake" is done intentionally to show that even though I should receive a value, there is a null pointer.

**Comment by CezaryBD** [comment]
@altro3 Please re-open this issue. The _a_ prefix is added to show that the getter is indeed not supposed to work!

**Comment by altro3** [comment]
All works fine. I checked it. You have NPE, becuase you try to read wrong field `aTemperature` as Float value. Of course `aTemperature` value will be null and whe you try to cast null to primitive `float` you have NPE. Getter works fine

**Comment by CezaryBD** [comment]
@altro3 I have updated my example, sorry for being not precise enough. I have made the eTemperature property not required. If you instead name the property as **temperature**, test passes.

**Comment by altro3** [comment]
@CezaryBD Sorry, I reely don't understand what you want to show. You're writing a test that doesn't work from the start. You seee this exception:
```
java.lang.NullPointerException: Cannot invoke "java.lang.Float.floatValue()" because the return value of "org.openapitools.model.CurrentWeather.geteTemperature()" is null
```

In the eTemperature field you have a null, because you do not pass this field. Then you try to do unboxing type float. Of course, null cannot be converted to a primitive and you get NPE

**Comment by altro3** [comment]
@CezaryBD I tried again your last sample project. That's my generated files:

`WeatherForecastApisApi.java`
```java
package org.openapitools.api;

import io.micronaut.http.annotation.*;
import io.micronaut.core.annotation.*;
import io.micronaut.http.client.annotation.Client;
import io.micronaut.core.convert.format.Format;
import reactor.core.publisher.Mono;
import org.openapitools.model.CurrentWeather;
import reactor.core.publisher.Mono;
import org.openapitools.model.V1ForecastGet400Response;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;

@Client("${openapi-micronaut-client-base-path}")
public interface WeatherForecastApisApi {

    /**
     * {@summary 7 day weather forecast for coordinates}
     * 7 day weather variables in hourly and daily resolution for given WGS84 latitude and longitude coordinates. Available worldwide.
     *
     * @param latitude WGS84 coordinate (required)
     * @param longitude WGS84 coordinate (required)
     * @param hourly (optional)
     * @param daily (optional)
     * @param currentWeather (optional)
     * @param temperatureUnit (optional, default to celsius)
     * @param windspeedUnit (optional, default to kmh)
     * @param timeformat If format &#x60;unixtime&#x60; is selected, all time values are returned in UNIX epoch time in seconds. Please not that all time is then in GMT+0! For daily values with unix timestamp, please apply &#x60;utc_offset_seconds&#x60; again to get the correct date. (optional, default to iso8601)
     * @param timezone If &#x60;timezone&#x60; is set, all timestamps are returned as local-time and data is returned starting at 0:00 local-time. Any time zone name from the [time zone database](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) is supported. (optional)
     * @param pastDays If &#x60;past_days&#x60; is set, yesterdays or the day before yesterdays data are also returned. (optional)
     * @return Mono&lt;CurrentWeather&gt;
     */
    @Get("/v1/forecast")
    Mono<CurrentWeather> v1ForecastGet(
        @QueryValue("latitude") @NotNull Float latitude,
        @QueryValue("longitude") @NotNull Float longitude,
        @QueryValue("hourly") @Nullable List<String> hourly,
        @QueryValue("daily") @Nullable List<String> daily,
        @QueryValue("current_weather") @Nullable Boolean currentWeather,
        @QueryValue(value = "temperature_unit", defaultValue = "celsius") @Nullable String temperatureUnit,
        @QueryValue(value = "windspeed_unit", defaultValue = "kmh") @Nullable String windspeedUnit,
        @QueryValue(value = "timeformat", defaultValue = "iso8601") @Nullable String timeformat,
        @QueryValue("timezone") @Nullable String timezone,
        @QueryValue("past_days") @Nullable Integer pastDays
    );
}
```

`V1ForecastGet400Response`
```java
package org.openapitools.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.stream.Collectors;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Introspected;
import io.micronaut.core.annotation.Nullable;

/**
 * V1ForecastGet400Response
 */
@Serdeable
@JsonPropertyOrder({
    V1ForecastGet400Response.JSON_PROPERTY_ERROR,
    V1ForecastGet400Response.JSON_PROPERTY_REASON
})
@Introspected
public class V1ForecastGet400Response {

    public static final String JSON_PROPERTY_ERROR = "error";
    public static final String JSON_PROPERTY_REASON = "reason";

    /**
     * Always set true for errors
     */
    @Nullable
    @JsonProperty(JSON_PROPERTY_ERROR)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private Boolean error;

    /**
     * Description of the error
     */
    @Nullable
    @JsonProperty(JSON_PROPERTY_REASON)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String reason;

    /**
     * Always set true for errors
     *
     * @return the error property value
     */
    public Boolean getError() {
        return error;
    }

    /**
     * Set the error property value
     */
    public void setError(Boolean error) {
        this.error = error;
    }

    /**
     * Set error in a chainable fashion.
     *
     * @return The same instance of V1ForecastGet400Response for chaining.
     */
    public V1ForecastGet400Response error(Boolean error) {
        this.error = error;
        return this;
    }

    /**
     * Description of the error
     *
     * @return the reason property value
     */
    public String getReason() {
        return reason;
    }

    /**
     * Set the reason property value
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * Set reason in a chainable fashion.
     *
     * @return The same instance of V1ForecastGet400Response for chaining.
     */
    public V1ForecastGet400Response reason(String reason) {
        this.reason = reason;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1ForecastGet400Response v1ForecastGet400Response = (V1ForecastGet400Response) o;
        return Objects.equals(error, v1ForecastGet400Response.error) &&
            Objects.equals(reason, v1ForecastGet400Response.reason);
    }

    @Override
    public int hashCode() {
        return Objects.hash(error, reason);
    }

    @Override
    public String toString() {
        return "V1ForecastGet400Response("
            + "error: " + getError() + ", "
            + "reason: " + getReason()
            + ")";
    }

}
```

`CurrentWeather.java`
```java
package org.openapitools.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.stream.Collectors;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Introspected;
import io.micronaut.core.annotation.Nullable;

/**
 * CurrentWeather
 */
@Serdeable
@JsonPropertyOrder({
    CurrentWeather.JSON_PROPERTY_TIME,
    CurrentWeather.JSON_PROPERTY_E_TEMPERATURE,
    CurrentWeather.JSON_PROPERTY_WINDSPEED,
    CurrentWeather.JSON_PROPERTY_WINDDIRECTION,
    CurrentWeather.JSON_PROPERTY_WEATHERCODE
})
@Introspected
public class CurrentWeather {

    public static final String JSON_PROPERTY_TIME = "time";
    public static final String JSON_PROPERTY_E_TEMPERATURE = "eTemperature";
    public static final String JSON_PROPERTY_WINDSPEED = "windspeed";
    public static final String JSON_PROPERTY_WINDDIRECTION = "winddirection";
    public static final String JSON_PROPERTY_WEATHERCODE = "weathercode";

    @NotNull
    @JsonProperty(JSON_PROPERTY_TIME)
    private String time;

    @Nullable
    @JsonProperty(JSON_PROPERTY_E_TEMPERATURE)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private Float eTemperature;

    @NotNull
    @JsonProperty(JSON_PROPERTY_WINDSPEED)
    private Float windspeed;

    @NotNull
    @JsonProperty(JSON_PROPERTY_WINDDIRECTION)
    private Float winddirection;

    @NotNull
    @JsonProperty(JSON_PROPERTY_WEATHERCODE)
    private Integer weathercode;

    public CurrentWeather(String time, Float windspeed, Float winddirection, Integer weathercode) {
        this.time = time;
        this.windspeed = windspeed;
        this.winddirection = winddirection;
        this.weathercode = weathercode;
    }

    /**
     * @return the time property value
     */
    public String getTime() {
        return time;
    }

    /**
     * Set the time property value
     */
    public void setTime(String time) {
        this.time = time;
    }

    /**
     * Set time in a chainable fashion.
     *
     * @return The same instance of CurrentWeather for chaining.
     */
    public CurrentWeather time(String time) {
        this.time = time;
        return this;
    }

    /**
     * @return the eTemperature property value
     */
    public Float geteTemperature() {
        return eTemperature;
    }

    /**
     * Set the eTemperature property value
     */
    public void seteTemperature(Float eTemperature) {
        this.eTemperature = eTemperature;
    }

    /**
     * Set eTemperature in a chainable fashion.
     *
     * @return The same instance of CurrentWeather for chaining.
     */
    public CurrentWeather eTemperature(Float eTemperature) {
        this.eTemperature = eTemperature;
        return this;
    }

    /**
     * @return the windspeed property value
     */
    public Float getWindspeed() {
        return windspeed;
    }

    /**
     * Set the windspeed property value
     */
    public void setWindspeed(Float windspeed) {
        this.windspeed = windspeed;
    }

    /**
     * Set windspeed in a chainable fashion.
     *
     * @return The same instance of CurrentWeather for chaining.
     */
    public CurrentWeather windspeed(Float windspeed) {
        this.windspeed = windspeed;
        return this;
    }

    /**
     * @return the winddirection property value
     */
    public Float getWinddirection() {
        return winddirection;
    }

    /**
     * Set the winddirection property value
     */
    public void setWinddirection(Float winddirection) {
        this.winddirection = winddirection;
    }

    /**
     * Set winddirection in a chainable fashion.
     *
     * @return The same instance of CurrentWeather for chaining.
     */
    public CurrentWeather winddirection(Float winddirection) {
        this.winddirection = winddirection;
        return this;
    }

    /**
     * @return the weathercode property value
     */
    public Integer getWeathercode() {
        return weathercode;
    }

    /**
     * Set the weathercode property value
     */
    public void setWeathercode(Integer weathercode) {
        this.weathercode = weathercode;
    }

    /**
     * Set weathercode in a chainable fashion.
     *
     * @return The same instance of CurrentWeather for chaining.
     */
    public CurrentWeather weathercode(Integer weathercode) {
        this.weathercode = weathercode;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CurrentWeather currentWeather = (CurrentWeather) o;
        return Objects.equals(time, currentWeather.time) &&
            Objects.equals(eTemperature, currentWeather.eTemperature) &&
            Objects.equals(windspeed, currentWeather.windspeed) &&
            Objects.equals(winddirection, currentWeather.winddirection) &&
            Objects.equals(weathercode, currentWeather.weathercode);
    }

    @Override
    public int hashCode() {
        return Objects.hash(time, eTemperature, windspeed, winddirection, weathercode);
    }

    @Override
    public String toString() {
        return "CurrentWeather("
            + "time: " + getTime() + ", "
            + "eTemperature: " + geteTemperature() + ", "
            + "windspeed: " + getWindspeed() + ", "
            + "winddirection: " + getWinddirection() + ", "
            + "weathercode: " + getWeathercode()
            + ")";
    }

}
```

**Comment by altro3** [comment]
@CezaryBD Compare your generated code with mine. I test it with current snapshot, maybe this bug was already fixed

**Comment by CezaryBD** [comment]
The issue is still not fixed for me. Additional info from Discord thread:
`It has been closed (although with no resolution), but I am still suffering from it.
The issue is simple, where you have an openapi specification with a declared property name starting with a single character like: sKlass.
If you are generating OpenAPI models out of it with Micronaut gradle plugin, it fails while resolving (reading) such property and falling back to null (so e.g. when reading a property from JSON file, sKlass is always null).
If you just change the property name to e.g. seKlass it will resolve property from JSON correctly without falling back to null.
There is a reproducible example in the issue linked above.
It is stopping me from using Micronaut Serialization and Serde. When using Jackson, everything works fine.
Thank you for looking into that, let me know if any questions.`

**Comment by altro3** [comment]
@CezaryBD I understood the problem from your last message. But please explain to me how this is related to micronaut-openapi? This module only generates a swagger file and has nothing to do with serialization and deserialization. This module does not participate in runtime at all, but is used only at the assembly stage. I showed you my screenshots of the generated swagger file - as you can see, all the fields are named correctly.

As I understand it, you have problems with serialization/deserialization using serde. If yes, then you need to open a ticket in this repository: https://github.com/micronaut-projects/micronaut-serialization

**Comment by altro3** [comment]
@dstepanov looks like this is serde issue

**Comment by altro3** [comment]
@dstepanov This is the classic problem with naming a field with a single lowercase letter. Jaxb has exactly the same problem. The only improvement that I can offer on my part is to force such fields in classes to be renamed. That is, JsonProperty will remain the same. but the field name in the java class will have the case of the second character changed.

But I don't think that's the problem. It seems that the field name from JsonProperty is not taken into account correctly in the serde module

**Comment by CezaryBD** [comment]
@dstepanov @altro3 is there any decision then? Will the issue be transferred to the different issue backlog? Thanks for any information.

**Comment by dstepanov** [comment]
Looks like the problem is somewhere in Core, this are not recognized as a traditional get/set:
```
    /**
     * @return the eTemperature property value
     */
    public Float geteTemperature() {
        return eTemperature;
    }

    /**
     * Set the eTemperature property value
     */
    public void seteTemperature(Float eTemperature) {
        this.eTemperature = eTemperature;
    }
```

Is there a way for the generator to rename the property in the code?

**Comment by dstepanov** [comment]
The generator might need to rename it to `ETemperature` or `etemperature`

**Comment by altro3** [comment]
According to 8.8: Capitalization of inferred names of the JavaBeans API specification the names generated from the IDE are correct.

Maybe, better to fix core? Because it will be a crutch that will correct one of all the problems

**Comment by altro3** [comment]
@CezaryBD @dstepanov fixed here: https://github.com/micronaut-projects/micronaut-core/pull/10130 . Don't want to create a crutch

**Comment by altro3** [comment]
@dstepanov Well, it's user decision and this is not prohibited by the java convention. So the user will decide for himself whether he likes it or not

**Comment by timyates** [comment]
This is a breaking change for when properties are all caps...  for a property ISBN, we used to generate (correctly) `getISBN()` we now generate `getiSBN()` which is incorrect

**Comment by altro3** [comment]
@timyates I think it would be more correct to call this a bug rather than a breaking change :-D
