### ISSUE TITLE
Other versions' response models included in all OpenAPIGroups

### ISSUE THREAD

**Issue by cweinberger** [micronaut-projects/micronaut-openapi#1534]
### Expected Behavior

When setting up two routes with same endpoints (but different versions, OpenAPI groups) it should not only use the respective routes/definitions, but also only the relevant response model.

Example:
```
@OpenAPIGroup("v1", exclude = ["v2"])
class ChargePointController {
    @Get("{chargePointId}")
    fun getChargePoint(
        request: HttpRequest<*>,
        @PathVariable
        chargePointId: Long
    ): ChargePointDto? { ... }
}

@OpenAPIGroup("v2", exclude = ["v1"])
class ChargePointV2Controller {
    @Get("{chargePointId}")
    fun getChargePoint(
        request: HttpRequest<*>,
        @PathVariable
        chargePointId: Long
    ): ChargePointV2Dto? { ... }
}
```

It should use `ChargePointDto` in v1 and `ChargePointV2Dto` in v2.

### Actual Behaviour

When both endpoints share the same path, in the response schema it is shown as oneOf(ChargePointDto, ChargePointV2Dto) in both v1 and v2.

It should use `ChargePointDto` in v1 and `ChargePointV2Dto` in v2.

**Screenshot of Swagger UI in v1**
(ChargePoint20240415 is supposed to be used in v2 only)
<img width="685" alt="Screenshot 2024-04-17 at 09 39 41" src="https://github.com/micronaut-projects/micronaut-openapi/assets/668808/f0368c9a-d796-4d96-901d-218aa0d4286c">

### Steps To Reproduce

Example project: https://github.com/cweinberger/micronaut-openapi-demo-1534

Generated Swagger files: https://github.com/micronaut-projects/micronaut-openapi/issues/1534#issuecomment-2061222978

### Environment Information

macOS 14.2.1 (23C71)
io.micronaut.openapi.annotation 6.5.1

### Version

4.3.9

**Comment by altro3** [comment]
Ok, I'l check it. But could you add sample applcation to reproduce this  problem? This will speed up the solution to the problem

**Comment by cweinberger** [comment]
@altro3 thanks for looking into it! Added a sample project here: https://github.com/cweinberger/micronaut-openapi-demo-1534

Generated yml files:
`swagger-v1.yml`
```
openapi: 3.0.1
paths:
  /demo:
    get:
      operationId: indexV1
      responses:
        "200":
          description: indexV2 200 response
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/HelloResponseV2'
                - $ref: '#/components/schemas/HelloResponseV1'
              example: null
components:
  schemas:
    HelloResponseV1:
      required:
      - message
      type: object
      properties:
        message:
          type: string
    HelloResponseV2:
      required:
      - message
      type: object
      properties:
        message:
          type: string
```

`swagger-v2.yml`
```
openapi: 3.0.1
paths:
  /demo:
    get:
      operationId: indexV2
      responses:
        "200":
          description: indexV2 200 response
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/HelloResponseV2'
                - $ref: '#/components/schemas/HelloResponseV1'
              example: null
components:
  schemas:
    HelloResponseV1:
      required:
      - message
      type: object
      properties:
        message:
          type: string
    HelloResponseV2:
      required:
      - message
      type: object
      properties:
        message:
          type: string
```

**Comment by altro3** [comment]
Ok, I'll check it on the weekend

**Comment by altro3** [comment]
fixed, wait release `6.9.0`

**Comment by cweinberger** [comment]
Amazing @altro3 Thanks a ton!

**Comment by cweinberger** [comment]
@altro3 It seems that this issue is still there (tested with 6.10.0 and 6.9.0).
<img width="920" alt="Screenshot 2024-05-31 at 09 50 32" src="https://github.com/micronaut-projects/micronaut-openapi/assets/668808/0bb3c897-34e7-4c44-8d5b-754647975a6f">

Demo project here https://github.com/cweinberger/micronaut-openapi-demo-1534/tree/openapi-annotations-6.10.0

**Comment by altro3** [comment]
Your sample works fine. Maybe it was a cache, or you use wrong version of micrnuat-openapi (you didn't set version in dependencies).

That's what I see when run build in your example:

![изображение](https://github.com/micronaut-projects/micronaut-openapi/assets/48474279/840fa5d3-c326-4da0-9aea-75139d01deb6)


But I set correct version of micronaut-openapi in dependencies:

![изображение](https://github.com/micronaut-projects/micronaut-openapi/assets/48474279/03a83419-3f17-4dd4-a319-fd6a72db3602)

**Comment by cweinberger** [comment]
You are absolutely right, sorry! 🙈 

Thanks a ton! 🙏
