### ISSUE TITLE
Classes not generated correctly when if/then is used

### ISSUE THREAD

**Issue by andlbrei** [micronaut-projects/micronaut-openapi#1797]
### Expected Behavior

- Expect items in`aListOfThings` to get a generated class. (Parent declares the array as a list of `any`, and no class is generated for the items in the array)
- Expect enum class to be generated from the `purpose` property within the array item.

### Actual Behaviour

When using `if/then` in an `allOf` to set required property I experience the following:

- No class is generated for the items in the array `aListOfThings`.
- Enum class generated for `purpose` property in the array item is empty.

### Steps To Reproduce

See https://github.com/andlbrei/micronaut-openapi-enum-reprod

### Environment Information

MacOS 15
temurin-21

### Example Application

https://github.com/andlbrei/micronaut-openapi-enum-reprod

### Version

4.6.2

**Comment by altro3** [comment]
All works fine, just use latest version of micronaut-openapi:

<img width="387" alt="{FF707C6D-7980-4088-AE7C-6D297CDF5C9F}" src="https://github.com/user-attachments/assets/41afb961-5105-4c1b-aaf1-d08837599f6e">

**Comment by altro3** [comment]
Oh, I see what problem is it now. I think json schema support (for OpenAPI 3.1.0) is very limited in openapi generator. 

I checked it with openapi-generator gradle plugin with spring generator - the same. You can create an issue here: https://github.com/OpenAPITools/openapi-generator/issues

**Comment by andlbrei** [comment]
Ok, thanks for your quick reply!

Your documentation states that you support OpenAPI 3.X, but it should actually be 3.0?

It's hard for me to know how this library uses openapi-generator under the hood.
Do you have any information you can give me on how to set up a reproduction for them that would act the same way as when using micronaut-openapi?

**Comment by altro3** [comment]
We use openapi-generator like everyone else - it stores our templates, which we use to generate classes. The only difference from the standard generator is that ours is launched using our plugin. This decision was made because the openapi-generator project is almost dead and the founders of this project are no longer involved in it. And we would like to release changes more often than once every six months :-)

As for support for 3.1 - no one has tested it, as far as I understand, some things work, and some don't. Openapi-generator claims that it supports version 3.1, but as you can see, support is full of bugs. I think that in their repo you will find dozens more of the described problems.

Yes, we can fix this bug directly for micronaut in this project. But personally, I don't need it at the moment. If you want, you can do it yourself. Create a PR - we will review it and merge it.

P.S. I am not part of the micronaut team. I just like micronaut and I am a very ordinary contributor. No one stops you from doing the same ;-)

**Comment by altro3** [comment]
About meesage with support OpenAPI 3.1.0:

From openapi-generator sources:
```
Generation using 3.1.0 specs is in development and is not officially supported yet.
If you would like to expedite development, please consider working on the open issues in the 3.1.0 project: https://github.com/orgs/OpenAPITools/projects/4/views/1
and reach out to our team on Slack at https://join.slack.com/t/openapi-generator/shared_invite/zt-12jxxd7p2-XUeQM~4pzsU9x~eGLQqX2g
```
From micronaut-openapi documentation:
```
Micronaut includes support for producing [OpenAPI](https://www.openapis.org/) (Swagger) YAML at compilation time. Micronaut will at compile time produce a OpenAPI 3.x compliant YAML file just based on the regular Micronaut annotations and the javadoc comments within your code.
```

Main thing: `support for producing [OpenAPI](https://www.openapis.org/) (Swagger) YAML at compilation time`. It means OpenAPI 3.1.0 supports by micronaut-openapi main module, not full project.

Micronaut openapi generator has the same limitations as original opanpi-generator, because it's based of it.

So, need to create an issue in openapi-generator repo

**Comment by andlbrei** [comment]
I want to inform that this issue has been solved in https://github.com/OpenAPITools/openapi-generator/pull/19964 and is expected to be released in openapi-generator 7.10.0

**Comment by altro3** [comment]
ok, great!

**Comment by altro3** [comment]
@andlbrei But as I understand, `if-else` still doesn't support in OpenAPI geenrator

**Comment by andlbrei** [comment]
> @andlbrei But as I understand, `if-else` still doesn't support in OpenAPI geenrator

Yes, I think this was a fix to make sure the fields are generated. It just removes the if/then.
Not ideal, but works for my case.
Hopefully we get more 3.1 support soon

**Comment by altro3** [comment]
It seems that if you want to see support for openapi 3.1, you'd better do it yourself and contribute to the generator. As far as I can see, work on this feature has long been stopped: https://github.com/orgs/OpenAPITools/projects/4/views/1

**Comment by andlbrei** [comment]
That project was started by someone who used to be a contributor, who left because of some disagreements and made a fork which has decent 3.1 support I think.
I believe they add some 3.1 stuff here and there, but they don't use that project that he made.
I have been tempted to try implementing some stuff, but getting to know that codebase seems like a fairly big task.
They responded quickly to this issue, so I'll try creating issues with as good of information and reproductions as I can, and hopefully that co-operation will result in some improvement and me learning more about how to fix some stuff myself.

I see you are contributing a lot here, great work
